version: '3.8'


services:

  formare:
<<<<<<< HEAD
    image: ion21/new-formare-service:14.05.2024.07.02.57
=======
    image: ion21/new-api-formare:14.05.2024.07.30.13
>>>>>>> a96c80fd25fff05feb531fc035092dddc74190c8

    network_mode: "host"
    environment:
      #      MYSQL_ROOT_PASSWORD: 'root'
      URL1: jdbc:mysql://192.168.0.112:3306/
      PASS1: R@0t
      USER1: root
      SPRING_PROFILES_ACTIVE: test
    ports:
      - "8080:8080"

#  client:
#    image: ion21/client-service:07.05.2024.11.11.15
#    networks:
#      - mynet
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=development
#      - REACT_APP_PATH_TO=development
#      - REACT_APP_API_URL=http://34.247.255.42:5000
#
#    depends_on:
#      - edge

