version: '3.8'


services:

  formare:
    image: ion21/new-formare-service:06.06.2024.15.20.29
    network_mode: "host"
    environment:
      #      MYSQL_ROOT_PASSWORD: 'root'
      URL1: jdbc:mysql://192.168.0.112:3306/
      PASS1: R@0t
      USER1: root
#      SPRING_PROFILES_ACTIVE: test
#    ports:
#      - "8080:8080"
