name: CD - Deploy Docker Compose

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: List files in the root of the repository
        run: |
            pwd
            ls -la

      - name: Deploy to MyServer
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
          mkdir -p ~/.ssh
          echo "${{ secrets.NOIP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no ./docker-compose.yaml ubuntus@${{ env.NOIP_INSTANCE_IP }}:/home/ubuntus/scripts/docker-compose.yaml
          ssh -o StrictHostKeyChecking=no ubuntus@${{ env.NOIP_INSTANCE_IP }} "\
            cd /home/ubuntus/scripts/ && ./initdocker.sh && \
            CONTAINERS=$(docker container ls -aq) && \
            if [ ! -z \"$CONTAINERS\" ]; then \
            docker container stop $CONTAINERS || true; \
            docker container rm $CONTAINERS || true; \
            fi; \
            echo 'Starting new containers...'; \
            docker-compose up -d; \
            echo 'Deployment completed successfully.'"
        env:
          NOIP_SSH_PRIVATE_KEY: ${{ secrets.NOIP_SSH_PRIVATE_KEY }}
          NOIP_INSTANCE_IP: 78.96.25.131
